// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17xI_vWcC-N3P-C2TPx4hknFZD2fWXfo',
    appId: '1:876562850199:android:4132000b59e7b8362ee4d2',
    messagingSenderId: '876562850199',
    projectId: 'todoapp-3cc79',
    authDomain: 'todoapp-3cc79.firebaseapp.com',
    storageBucket: 'e-voting-9ab22.appspot.com',
    measurementId: 'G-4TWFLSE65Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALfTAu8KMNjJOSwx8DknjaXt8aeUffDRs',
    appId: '1:210009114284:android:55b5ef9eba20459c8e8109',
    messagingSenderId: '210009114284',
    projectId: 'e-voting-9ab22',
    storageBucket: 'e-voting-9ab22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlOyEFAAD_OkavPy55iNY-46aoUR6b-i8',
    appId: '1:210009114284:ios:6deb5d49aaf544858e8109',
    messagingSenderId: '210009114284',
    projectId: 'e-voting-9ab22',
    storageBucket: 'e-voting-9ab22.appspot.com',
    iosBundleId: 'com.example.eVoting',
  );
}
